//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мухутдинов.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spisanie
    {
        public long ID_spis { get; set; }
        public Nullable<long> ID_knigi { get; set; }
        public string Nazvanie_knigi { get; set; }
        public string Nameavtory { get; set; }
        public string Vidizdanie { get; set; }
        public string Izdatelstvo { get; set; }
        public Nullable<System.DateTime> Date_spis { get; set; }
        public string Prichina { get; set; }
    
        public virtual Knigi Knigi { get; set; }
    }
}
